apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: your-nginx-image:tag
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: myconfig
          env:
            - name: WORD1
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: word1
            # Repeat for WORD2, WORD3, WORD4, and WORD5
            - name: SERVER_FQDN
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: server-fqdn
      volumes:
        - name: certs-volume
          secret:
            secretName: sitecert
            defaultMode: 420
