apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
        - name: nginx-web
          image: eilerb101/nginx-configmap:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: myconfig
          env:
            - name: word1
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: word1
            - name: word2
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: word2
            - name: word3
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: word3
            - name: word4
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: word4
            - name: word5
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: word5
            - name: banner
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: banner
            - name: boxcolor
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: boxcolor
            - name: bannercolor
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: bannercolor
            - name: background
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: background
            - name: user
              valueFrom:
                secretKeyRef:
                  name: sitepass
                  key: user
            - name: htpass
              valueFrom:
                secretKeyRef:
                  name: sitepass
                  key: htpass
